### ISSUE TITLE
buster command not working on Mac OS X

### ISSUE THREAD

**Issue by myKingEdem** [axitkhurana/buster#8]

**Comment by axitkhurana** [comment]
Hey @rkcudjoe 

Can you give more details about the problem?

**Comment by myKingEdem** [comment]
I gave up, now I'm using ghost-buster by modulus.io

**Comment by axitkhurana** [comment]
Oh, I would be happy to help if you could give me more details about the error. I'm running it on OS X so that shouldn't be a problem.

If you're willing to give it another shot, you can checkout these [simple instructions](http://metacotta.com/ghost-static-site-generation-with-buster/) to get started written by one of the users.

Feel free to open another issue with traceback/console output of the error in case you face any problem with the instructions above.
